# Generated by Django 4.2.6 on 2023-10-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='usermaname',
            new_name='username',
        ),
    ]
