# Generated by Django 4.2.5 on 2023-10-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_usermaname_employees_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='password',
            field=models.CharField(default='12345678', max_length=50),
        ),
    ]
